[package]
name = "focusfit-minter"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.14", features = ["abigen"] }
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"
